version: '{build}'
branches:
  except:
    - '/^wip/'
    - '/^blocked/'
shallow_clone: true

environment:
  matrix:
    - perl_type: system
    - perl_type: strawberry
    - perl_type: strawberry
      perl_version: 5.12.3.1
    - perl_type: strawberry
      perl_version: 5.16.3.3
    - perl_type: strawberry
      perl_version: 5.20.1.1
    - perl_type: cygwin

install:
  - 'call .appveyor.cmd perl_setup'
  - '%perl% -V'
  - '%cpanm% --installdeps -n --with-develop --with-recommends .'

build: off

test_script:
  - 'prove -lv t xt'
  - 'set MOO_XS_DISABLE=1'
  - 'prove -lv t xt'
